//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka_TB
    {
        public int ID { get; set; }
        public string BankaAd { get; set; }
        public string Sube { get; set; }
        public string Iban { get; set; }
        public string HesapNo { get; set; }
        public string Yetkili { get; set; }
        public string Tarih { get; set; }
        public string HesapTuru { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Telefon { get; set; }
    }
}
