//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaDetay_TB
    {
        public int ID { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> FaturaBilgiId { get; set; }
    }
}
