//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaBilgi_TB
    {
        public int ID { get; set; }
        public string Seri { get; set; }
        public string SıraNo { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public string VergiDaire { get; set; }
        public string Alici { get; set; }
        public string TeslimEden { get; set; }
        public string TeslimAlan { get; set; }
    }
}
