//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma_TB
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string YetkiliStatu { get; set; }
        public string YetkiliAdSoyad { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Telefon3 { get; set; }
        public string Mail { get; set; }
        public string Fax { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string VergiDaire { get; set; }
        public string Adres { get; set; }
        public string YetkiliTC { get; set; }
        public string OzelKod1 { get; set; }
        public string OzelKod2 { get; set; }
        public string OzelKod3 { get; set; }
        public string Sektor { get; set; }
    }
}
