//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gider_TB
    {
        public int ID { get; set; }
        public Nullable<decimal> Elektrik { get; set; }
        public Nullable<decimal> Su { get; set; }
        public Nullable<decimal> DoğalGaz { get; set; }
        public Nullable<decimal> Internet { get; set; }
        public Nullable<decimal> Maaşlar { get; set; }
        public Nullable<decimal> Ekstra { get; set; }
        public string Detay { get; set; }
    }
}
