//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not_TB
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NotTarih { get; set; }
        public Nullable<System.TimeSpan> NotSaat { get; set; }
        public string NotBaslik { get; set; }
        public string NotDetay { get; set; }
        public string NotOlusturan { get; set; }
    }
}
