//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicariContext : DbContext
    {
        public TicariContext()
            : base("name=TicariContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banka_TB> Banka_TB { get; set; }
        public virtual DbSet<FaturaBilgi_TB> FaturaBilgi_TB { get; set; }
        public virtual DbSet<FaturaDetay_TB> FaturaDetay_TB { get; set; }
        public virtual DbSet<Firma_TB> Firma_TB { get; set; }
        public virtual DbSet<Gider_TB> Gider_TB { get; set; }
        public virtual DbSet<Ilceler_TB> Ilceler_TB { get; set; }
        public virtual DbSet<Iller_TB> Iller_TB { get; set; }
        public virtual DbSet<Musteri_TB> Musteri_TB { get; set; }
        public virtual DbSet<Not_TB> Not_TB { get; set; }
        public virtual DbSet<Personel_TB> Personel_TB { get; set; }
        public virtual DbSet<Stok_TB> Stok_TB { get; set; }
        public virtual DbSet<Urun_TB> Urun_TB { get; set; }
        public virtual DbSet<Kodlar_TB> Kodlar_TB { get; set; }
        public virtual DbSet<Admin_TB> Admin_TB { get; set; }
    }
}
